@WebApplication1_HostAddress = http://localhost:8080

GET {{WebApplication1_HostAddress}}/api/todo-items
Accept: application/json

###

POST {{WebApplication1_HostAddress}}/api/todo-item
Content-Type: application/json

{
	"title": "learn asp.net core"
}

###

DELETE {{WebApplication1_HostAddress}}/api/todo-item/1

###
