services:
  todoservice:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: todoservice
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
